### ISSUE TITLE
downgrade typescript (temporary)

### ISSUE THREAD

**Issue by tamascsaba** [kaloczidev/nyfk-angular#1]
Follow: https://github.com/s-panferov/awesome-typescript-loader/issues/293

**Comment by tamascsaba** [comment]
:8ball:

**Comment by kaloczidev** [comment]
:hammer: :hamburger: :cheese:

**Comment by tamascsaba** [comment]
Releted commit: https://github.com/kaloczidev/nyfk-angular/commit/2118f129ba27b18900887262feabffab56bb6767
